[package]
name = "geoesg-aeco-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Framework & Async
axum = "0.7"
tokio = { version = "1.36", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }

# Serialization & Parsing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.6" # High-level XML parsing
quick-xml = { version = "0.31", features = ["serialize"] }

# Networking & Scheduling
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
tokio-cron-scheduler = "0.10"
dotenvy = "0.15"

# Utility
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
gdal = { version = "0.19.0", features = ["bindgen"] }

[patch.crates-io]
gdal = { git = "https://github.com/georust/gdal", rev = "968cf34a" }
gdal-sys = { git = "https://github.com/georust/gdal", rev = "968cf34a" }
